POST https://fastify-node-ai-example.onrender.com/videos
Content-Type: application/json

{
  "title": "Vídeo node",
  "description": "Esse é o primeiro vídeo.",
  "duration": 180
}

###

GET https://fastify-node-ai-example.onrender.com/videos?search=node

###

PUT https://fastify-node-ai-example.onrender.com/videos/bba33c67-f07d-46c6-8cfc-068e5b25a1d2
Content-Type: application/json

{
  "title": "Vídeo 02",
  "description": "Esse é o segundo vídeo.",
  "duration": 180
}

###

DELETE https://fastify-node-ai-example.onrender.com/videos/bba33c67-f07d-46c6-8cfc-068e5b25a1d2
